services:
  ds-storage:
    image: ds-storage/master:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ds-storage
      secrets:
        - maven_settings
        - maven_settings_security
    cap_drop:
      - ALL
    container_name: ds-storage
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      TZ: UTC
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://ds-storage:8080/ds-storage/v1/monitor/status" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 25s
    ports:
      - "8081:8080"
    env_file:
      - aegis/docker/ds-backend/.env
    networks:
      - ds_archive_network
    security_opt:
      - no-new-privileges:true

  ds-license:
    image: ds-license/master:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ds-license
      secrets:
        - maven_settings
        - maven_settings_security
    cap_drop:
      - ALL
    container_name: ds-license
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      TZ: UTC
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://ds-license:8080/ds-license/v1/monitor/status" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 25s
    ports:
      - "8082:8080"
    env_file:
      - aegis/docker/ds-backend/.env
    networks:
      - ds_archive_network
    security_opt:
      - no-new-privileges:true

  ds-present:
    image: ds-present/master:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ds-present
      secrets:
        - maven_settings
        - maven_settings_security
    cap_drop:
      - ALL
    container_name: ds-present
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      TZ: UTC
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://ds-present:8080/ds-present/v1/monitor/status" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 25s
    ports:
      - "8083:8080"
    env_file:
      - aegis/docker/ds-backend/.env
    networks:
      - ds_archive_network
    security_opt:
      - no-new-privileges:true

  ds-datahandler:
    image: ds-datahandler/master:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ds-datahandler
      secrets:
        - maven_settings
        - maven_settings_security
    cap_drop:
      - ALL
    container_name: ds-datahandler
    depends_on:
      keycloak:
        condition: service_healthy
      solr:
        condition: service_healthy
    environment:
      TZ: UTC
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://ds-datahandler:8080/ds-datahandler/v1/monitor/status" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 25s
    ports:
      - "8084:8080"
    env_file:
      - aegis/docker/ds-backend/.env
    networks:
      - ds_archive_network
    security_opt:
      - no-new-privileges:true

  ds-discover:
    image: ds-discover/master:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ds-discover
      secrets:
        - maven_settings
        - maven_settings_security
    cap_drop:
      - ALL
    container_name: ds-discover
    depends_on:
      keycloak:
        condition: service_healthy
      solr:
        condition: service_healthy
    environment:
      TZ: UTC
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://ds-discover:8080/ds-discover/v1/monitor/status" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 25s
    ports:
      - "8085:8080"
    env_file:
      - aegis/docker/ds-backend/.env
    networks:
      - ds_archive_network
    security_opt:
      - no-new-privileges:true

  ds-image:
    image: ds-image/master:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ds-image
      secrets:
        - maven_settings
        - maven_settings_security
    cap_drop:
      - ALL
    container_name: ds-image
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      TZ: UTC
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://ds-image:8080/ds-image/v1/monitor/status" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 25s
    ports:
      - "8086:8080"
    env_file:
      - aegis/docker/ds-backend/.env
    networks:
      - ds_archive_network
    security_opt:
      - no-new-privileges:true

  bff:
    image: bff/master:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: bff
      secrets:
        - maven_settings
        - maven_settings_security
    cap_drop:
      - ALL
    container_name: ds-bff
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      TZ: UTC
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://bff:8080/bff/v1/monitor/status" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 25s
    ports:
      - "8091:8080"
    env_file:
      - aegis/docker/ds-backend/.env
    networks:
      - ds_archive_network
    security_opt:
      - no-new-privileges:true

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0-1
    command: [ "start-dev", "--import-realm", "--http-port=8087" ]
    cap_drop:
      - ALL
    container_name: ds-keycloak
    environment:
      TZ: UTC
      KC_BOOTSTRAP_ADMIN_USERNAME: user
      KC_BOOTSTRAP_ADMIN_PASSWORD: changeit
      KC_HTTP_ENABLED: true
      # Sets the uniform identity for token issuance across your entire environment
      KC_HOSTNAME: http://keycloak.local:8087
      KC_HEALTH_ENABLED: true
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /tmp/HealthCheck.java ] || echo 'public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }' > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "8087:8087"
    networks:
      ds_archive_network:
        aliases:
          - keycloak.local
    volumes:
      - ./conf/keycloak:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data
    security_opt:
      - no-new-privileges:true

  postgres:
    image: postgres:13.23-alpine3.21
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    container_name: ds-postgres
    environment:
      TZ: UTC
      POSTGRES_DB: digisam
      POSTGRES_USER: digisam
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=digisam" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "8088:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./conf/postgres/apply-ordered-sql.sh:/docker-entrypoint-initdb.d/apply-ordered-sql.sh:ro
      - ./conf/postgres/order.txt:/init-scripts/order.txt:ro
      - ./ds-datahandler/src/test/resources/ddl/create_ds_datahandler_db.ddl:/init-scripts/create_ds_datahandler_db.ddl:ro
      - ./ds-license/src/test/resources/ddl/licensemodule_create_db.ddl:/init-scripts/licensemodule_create_db.ddl:ro
      - ./ds-license/src/test/resources/ddl/audit_log_module_create_db.ddl:/init-scripts/audit_log_module_create_db.ddl:ro
      - ./ds-license/src/test/resources/ddl/rightsmodule_create.ddl:/init-scripts/rightsmodule_create.ddl:ro
      - ./ds-storage/src/test/resources/ddl/create_ds_storage.ddl:/init-scripts/create_ds_storage.ddl:ro
      - ./ds-license/src/test/resources/ddl/licensemodule_default_configuration.ddl:/init-scripts/licensemodule_default_configuration.ddl:ro
      - ./ds-license/src/test/resources/ddl/rightsmodule_create_db.ddl:/init-scripts/rightsmodule_create_db.ddl:ro
      - ./ds-license/src/test/resources/ddl/rightsmodule_default_dr_holdback_categories_data.sql:/init-scripts/rightsmodule_default_dr_holdback_categories_data.sql:ro
      - ./ds-license/src/test/resources/ddl/rightsmodule_default_dr_holdback_ranges_data.sql:/init-scripts/rightsmodule_default_dr_holdback_ranges_data.sql:ro
      - ./ds-license/src/test/resources/ddl/licensemodule_create_devel_license.sql:/init-scripts/licensemodule_create_devel_license.sql:ro
    networks:
      - ds_archive_network
    security_opt:
      - no-new-privileges:true

  solr:
    image: solr-image/master:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: solr
    cap_drop:
      - ALL
    container_name: ds-solr
    environment:
      TZ: UTC
      SOLR_MODULES: extraction,langid,ltr,analysis-extras,scripting
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://solr:8983/solr/ds-collection_shard1_replica_n1/admin/ping?wt=json" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - "8089:8983"
      - "9983:9983"
    env_file:
      - aegis/docker/ds-backend/.env
    command: [ "solr-foreground", "-c" ]
    volumes:
      - solr_data:/opt/solr/server/solr/writable
    networks:
      - ds_archive_network
    security_opt:
      - no-new-privileges:true

volumes:
  solr_data:
  keycloak_data:
  postgres_data:

secrets:
  maven_settings:
    file: ~/.m2/settings.xml
  maven_settings_security:
    file: ~/.m2/settings-security.xml

networks:
  ds_archive_network:
    name: ds_archive_network
    driver: bridge