info:
  name: Return a RerunClusterResponseDto from fileId. If no match was found, it return an RerunClusterResponseDto with null values in all fields, because the code can not handle null values or HTTP code 404 in a nice way
  type: http
  seq: 2
  tags:
    - RerunCluster

http:
  method: GET
  url: "{{baseUrl}}/rerun-cluster/:fileId"
  params:
    - name: fileId
      value: ""
      type: path
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: https://api.example.com/oauth2/authorize
    callbackUrl: "{{oauth_callback_url}}"
    credentials:
      clientId: "{{oauth_client_id}}"
    scope: generic_ds read write devel admin public any
    state: "{{oauth_state}}"
    tokenConfig:
      placement:
        header: Bearer
      source: access_token
    settings:
      autoFetchToken: false
      autoRefreshToken: true

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false

examples:
  - name: 200 Response
    description: Return the specific RerunClusterResponseDto. If no match was found, it return an RerunClusterResponseDto with null values in all fields, because the code can not handle null values or HTTP code 404 in a nice way.
    request:
      url: "{{baseUrl}}/rerun-cluster/:fileId"
      method: GET
      params:
        - name: fileId
          value: ""
          type: path
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "id": "",
            "fileId": "",
            "rerunClusterId": "",
            "rerunClusterIdCount": 0,
            "created": "",
            "jobId": "",
            "inserted": "",
            "updated": ""
          }
  - name: 404 Response
    description: Could not find RerunClusterResponseDto with fileId. How it should be, but the code can not handle it well.
    request:
      url: "{{baseUrl}}/rerun-cluster/:fileId"
      method: GET
      params:
        - name: fileId
          value: ""
          type: path
    response:
      status: 404
      statusText: Not Found
      body:
        type: text
        data: ""
